shallow_clone: true

os:
  - Visual Studio 2017

environment:
  matrix:
  - TOOLSET: vs2017

configuration:
  - debug-static
  - release-static

install:
  build\deploy_poco.cmd
  build\genproj.cmd

build:
  project: trader.sln
