version: 0.0.{build}

os:
  - Visual Studio 2017

environment:
  my_secret:
    secure: 1+nl/M+SEHCHODFx1uJfZA==
  my_github_username:
    secure: dVKOiMJnhBO0y+8aZxCYDg==
  my_github_password:
    secure: LcITt+0DCnllqTcdDo3Ee3yO+L0CWbGVNqwnfYgvQz3LPoQ3VZupN4rkvAQTrz8f
  my_code_cov_token:
    secure: 2iuD0Fo0vpxlatuUju4Exef+3iXN9QCVzp4t4nav6LHo1scj3awzLqo3kf4GCV4s
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
  matrix:
  - TOOLSET: vs2017
    VS_PLATFORM_TOOLSET: v141
  - TOOLSET: vs2015
    VS_PLATFORM_TOOLSET: v140

configuration:
  - debug-static
  - release-static
  - debug-shared
  - release-shared

install:
  - cmd: git submodule update --init --recursive
  - cmd: powershell -ExecutionPolicy Bypass -File .\build\deploy_tools.ps1
  - cmd: powershell -ExecutionPolicy Bypass -File .\build\decrypt_configs.ps1
  - cmd: tools\bin\premake\premake5.exe %TOOLSET%

before_build:
  - cmd: msbuild generators.sln /t:Build /p:Configuration="%configuration%" /p:PlatformToolset=%VS_PLATFORM_TOOLSET% /p:Platform=Win64

build:
  project: trader.sln

cache:
  - packages -> premake5.lua
  - tools -> build\deploy_tools.ps1, build\decrypt_configs.ps1

after_build:
  7z a trader_%configuration%_%APPVEYOR_BUILD_VERSION%.zip %APPVEYOR_BUILD_FOLDER%\bin\Win64\%configuration%\*.exe %APPVEYOR_BUILD_FOLDER%\bin\Win64\%configuration%\*.dll %APPVEYOR_BUILD_FOLDER%\bin\Win64\*.properties %APPVEYOR_BUILD_FOLDER%\bin\Win64\*.json

artifacts:
  - path: trader_%configuration%_%APPVEYOR_BUILD_VERSION%.zip

  - path: bin
    type: zip

deploy:
    # Deploy to GitHub Releases
  - provider: GitHub
    artifact: /.*\.zip/           # upload all zip packages to release assets
    draft: true
    prerelease: true
    on:
      branch: master                # release from master branch only
    auth_token:
      secure: cVIYLIIEjkS7RLb2rseOsIWW9ru4KNdKjA0bWfE6gVVsutQXo6uyodpau6al+YS+
#      appveyor_repo_tag: true       # deploy on tag push only

test_script:
  #Just name test executables as *test.exe and it will be part of the test coverage
  - cmd: powershell -ExecutionPolicy Bypass -File .\build\run_tests.ps1

after_test:
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -f "code_coverage_report.xml" -t $env:my_code_cov_token
