version: 0.0.{build}

os:
  - Visual Studio 2017

environment:
  my_secret:
    secure: 1+nl/M+SEHCHODFx1uJfZA==
  matrix:
  - TOOLSET: vs2017
    VS_PLATFORM_TOOLSET: v141
  - TOOLSET: vs2015
    VS_PLATFORM_TOOLSET: v140

configuration:
  - debug-static
  - release-static
  - debug-shared
  - release-shared

install:
  - cmd: git submodule update --init --recursive
  - cmd: powershell -ExecutionPolicy Bypass -File .\build\deploy_tools.ps1
  - ps: iex ((New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/appveyor/secure-file/master/install.ps1'))
  - cmd: appveyor-tools\secure-file -decrypt bin\trader.properties.enc -secret %my_secret%
  - cmd: appveyor-tools\secure-file -decrypt bin\bittrex.config.json.enc -secret %my_secret%
  - cmd: appveyor-tools\secure-file -decrypt bin\bittrex_api_test.properties.enc -secret %my_secret%
  - cmd: appveyor-tools\secure-file -decrypt bin\connection_interface_test.properties.enc -secret %my_secret%
  - cmd: appveyor-tools\secure-file -decrypt bin\exchangeratelab.config.json.enc -secret %my_secret%
  - cmd: appveyor-tools\secure-file -decrypt bin\kraken.config.json.enc -secret %my_secret%
  - cmd: appveyor-tools\secure-file -decrypt bin\sample_app_test.properties.enc -secret %my_secret%
  - cmd: build\genproj.cmd
#  - cmd: msbuild tmp\projects\genproj.vcxproj /t:Build /p:Configuration="debug-static Win64" /p:PlatformToolset=%VS_PLATFORM_TOOLSET% /p:SolutionDir=..\..\ -p:Platform=x64

before_build:
  - cmd: msbuild generators.sln /t:Build /p:Configuration="%configuration%" /p:PlatformToolset=%VS_PLATFORM_TOOLSET% /p:Platform=Win64

build:
  project: trader.sln

cache:
  - packages -> premake5.lua
  - tools -> build\deploy_tools.ps1

after_build:
  7z a trader_tests_%configuration%_%APPVEYOR_BUILD_VERSION %.zip %APPVEYOR_BUILD_FOLDER%\bin\Win64\%configuration%\*test.exe %APPVEYOR_BUILD_FOLDER%\bin\Win64\*.properties %APPVEYOR_BUILD_FOLDER%\bin\Win64\*.json

artifacts:
  - path: trader_tests_%configuration%_%APPVEYOR_BUILD_VERSION%.zip

  - path: bin
    type: zip

deploy:
    # Deploy to GitHub Releases
  - provider: GitHub
    artifact: /.*\.zip/           # upload all zip packages to release assets
    draft: true
    prerelease: true
    on:
      branch: master                # release from master branch only
    auth_token:
      secure: cVIYLIIEjkS7RLb2rseOsIWW9ru4KNdKjA0bWfE6gVVsutQXo6uyodpau6al+YS+
#      appveyor_repo_tag: true       # deploy on tag push only

test_script:
  - cmd: bin\Win64\%configuration%\bittrex_api_test.exe --gtest_output=xml:bittrex_api_test.xml
  - ps: (new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\bittrex_api_test.xml))
  - cmd: bin\Win64\%configuration%\connection_interface_test.exe --gtest_output=xml:connection_interface_test.xml
  - ps: (new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\connection_interface_test.xml))
  - cmd: bin\Win64\%configuration%\sample_app_test.exe --gtest_output=xml:sample_app_test.xml
  - ps: (new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\sample_app_test.xml))
