os:
  - Visual Studio 2017

environment:
  matrix:
  - TOOLSET: vs2017
    VS_PLATFORM_TOOLSET: v141
  - TOOLSET: vs2015
    VS_PLATFORM_TOOLSET: v140

configuration:
  - debug-static
  - release-static

install:
  - cmd: git submodule update --init --recursive
  - cmd: powershell -ExecutionPolicy Bypass -File .\build\deploy_tools.ps1
  - cmd: build\genproj.cmd
  - cmd: msbuild tmp\projects\genproj.vcxproj /t:Build /p:Configuration="debug-static Win64" /p:PlatformToolset=%VS_PLATFORM_TOOLSET% /p:SolutionDir=..\..\ -p:Platform=x64

before_build:
  - cmd: msbuild generators.sln /t:Build /p:Configuration="debug" /p:PlatformToolset=%VS_PLATFORM_TOOLSET% /p:Platform=Win64
  - cmd: msbuild generators.sln /t:Build /p:Configuration="release" /p:PlatformToolset=%VS_PLATFORM_TOOLSET% /p:Platform=Win64

build:
  project: trader.sln

cache:
  - packages -> premake5.lua
  - tools -> build\deploy_tools.ps1

after_build:
  7z a trader_tests_{{configuration}}_%APPVEYOR_BUILD_NUMBER%.zip %APPVEYOR_BUILD_FOLDER%\bin\Win64\{{configuration}}\*test.exe %APPVEYOR_BUILD_FOLDER%\bin\Win64\*.properties %APPVEYOR_BUILD_FOLDER%\bin\Win64\*.json

artifacts:
  - path: trader_tests_{{configuration}}_%APPVEYOR_BUILD_NUMBER%.zip

  - path: bin
    type: zip

deploy:
    # Deploy to GitHub Releases
  - provider: GitHub
    artifact: /.*\.zip/           # upload all zip packages to release assets
    draft: true
    prerelease: true
    on:
      branch: master                # release from master branch only
    auth_token:
      secure: cVIYLIIEjkS7RLb2rseOsIWW9ru4KNdKjA0bWfE6gVVsutQXo6uyodpau6al+YS+
#      appveyor_repo_tag: true       # deploy on tag push only