os:
  - Visual Studio 2017

environment:
  matrix:
  - TOOLSET: vs2017

configuration:
  - debug-static
  - release-static

install:
  - cmd: git submodule update --init --recursive
  - cmd: powershell -ExecutionPolicy Bypass -File .\build\deploy_tools.ps1
  - cmd: build\genproj.cmd
  - cmd: msbuild tmp\projects\genproj.vcxproj /t:Build /p:Configuration="debug-static Win64" /p:PlatformToolset=v141 /p:SolutionDir=..\..\ -p:Platform=x64

before_build:
  - cmd: msbuild generators.sln /t:Build /p:Configuration="debug" /p:PlatformToolset=v141 /p:Platform=Win64
  - cmd: msbuild generators.sln /t:Build /p:Configuration="release" /p:PlatformToolset=v141 /p:Platform=Win64

build:
  project: trader.sln

cache:
  - packages -> premake5.lua
  - tools -> build\deploy_tools.ps1
