os:
  - Visual Studio 2017

environment:
  matrix:
  - TOOLSET: vs2017

configuration:
  - debug-static
  - release-static

install:
  - cmd: git submodule update --init --recursive
  - cmd: build\deploy_tools.cmd
  - cmd: build\genproj.cmd

build:
  project: trader.sln

cache:
  - packages -> premake5.lua
  - tools -> build\deploy_tools.cmd
